<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
$boletoUrl = $block->getLinkPrintPay();
?>
<dl class="payment-method">
    <dt class="title"><?= /* @noEscape */ $title ?></dt>
    <dd class="content">
        <table class="data table">
            <caption class="table-caption"><?= /* @noEscape */ $title ?></caption>
        <?php if ($specificInfo):?>
            <?php foreach ($specificInfo as $label => $value):?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml($label) ?></th>
                    <td>
                        <?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif;?>
            <?php if ($boletoUrl):?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml('Link')?></th>
                    <td>
                        <a href="<?php echo $boletoUrl; ?>" class="btn btn-link" target="_blank">
                            Imprimir Boleto
                        </a>
                    </td>
                </tr>
            <?php endif;?>
        </table>

        <?php $_parcelas = $block->getParcelasCollection(); ?>
        <?php if (!empty($_parcelas)) : ?>
        <table class="data table table-order-items">
            <thead>
                <tr class="headings">
                    <?php $i = 0;
                    $columns = $block->getFrontColumns();
                    $lastItemNumber = count($columns) ?>
                    <?php foreach ($columns as $columnName => $columnTitle):?>
                        <?php $i++; ?>
                        <th class="col-<?= /* @noEscape */ $columnName ?><?= /* @noEscape */ ($i === $lastItemNumber ? ' last' : '') ?>"><span><?= /* @noEscape */ $columnTitle ?></span></th>
                    <?php endforeach; ?>
                </tr>
            </thead>
            <?php $i = 0; foreach ($_parcelas as $_parcela) : $i++ ?>
                <tbody class="<?= /* @noEscape */ $i%2 ? 'even' : 'odd' ?>">
                    <td class="col-parcela-number"><?= $block->getColumnHtml($_parcela, 'installment_number') ?></td>
                    <td class="col-parcela-due-date"><?= $block->getColumnHtml($_parcela, 'due_date') ?></td>
                    <td class="col-parcela-paid-amount"><?= $block->getColumnHtml($_parcela, 'paid_amount') ?></td>
                </tbody>
            <?php endforeach; ?>
        </table>
        <?php endif; ?>
    </dd>
</dl>
<?= $block->getChildHtml() ?>
