<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
$pixUrl = $block->getLinkPrintPay();
$pixExpiresAt = $block->getPixExpiresAtFormatted();
?>
<dl class="payment-method">
    <dt class="title"><?= /* @noEscape */ $title ?></dt>
    <dd class="content">
        <table class="data table">
            <caption class="table-caption"><?= /* @noEscape */ $title ?></caption>
        <?php if ($specificInfo):?>
            <?php foreach ($specificInfo as $label => $value):?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml($label) ?></th>
                    <td>
                        <?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        <?php endif;?>
            <?php if ($pixExpiresAt):?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml(__('QR Code válido até')) ?></th>
                    <td><?= $block->escapeHtml($pixExpiresAt) ?></td>
                </tr>
            <?php endif;?>
            <?php if ($pixUrl):?>
                <tr>
                    <th scope="row"><?= $block->escapeHtml('Link')?></th>
                    <td>
                        <a href="<?php echo $pixUrl; ?>" class="btn btn-link" target="_blank">
                            <?= /* @noEscape */ __('Visualizar QR Pix') ?>
                        </a>
                    </td>
                </tr>
            <?php endif;?>
        </table>
    </dd>
</dl>
<?= $block->getChildHtml() ?>
