<?php if($block->getMethodCode() === "ipagboleto"):
$url = "";
if (!empty($block->getInfo('urlAuthentication'))) {
    $url = $block->getInfo('urlAuthentication');
}
else {
    if (!empty($block->getInfo('attributes.links.payment'))) {
        $url = $block->getInfo('attributes.links.payment');
    }
}
?>
	<p>
		<a href="<?php echo $url; ?>" target="_blank" class="action primary btn-boleto boleto-ipag">
			<span><?php echo __('Imprimir Boleto') ?></span>
		</a>
	</p>
<?php endif; ?>
<?php if($block->getMethodCode() === "ipagpix") : 
	$qrCode = $block->getInfo('pix.qrCode');
	$qrHelper = $block->getQrHelper($qrCode);
	
	?>
	<div id="qr-info" class="col-md-6">
		<div class="card card-default">
			<div class="card-body">
				<div class="text-center m-4">
					<h3>Use o QR Code do Pix para pagar</h3>
					<p>Abra o app em que vai fazer o pagamento, escaneie a imagem ou cole o código do QR Code</p>
						<img class='rounded mw-100' src='<?php echo $qrHelper->writeDataUri()?> '/>
					<h3><?php echo $block->getGrandTotalFormatted(); ?></h3>
					<button type="button" id="button-copy" class="action primary btn-pix boleto-ipag">Copiar código do QR Code</button>
					<input type="hidden" id="brCode" value="<?php echo $qrCode; ?>">
				</div>
			</div>
		</div>
	</div>
	<script>
		var copyElement = document.getElementById("button-copy");

		copyElement.addEventListener('click', function() {
			copyText = document.getElementById("brCode");
			copyText.type = 'text';
			copyText.select();
			copyText.setSelectionRange(0, 99999);
			document.execCommand("copy");
			copyText.type = 'hidden';
		});

		copyElement.addEventListener('click', function () {
			copyElement.classList.add('copied-icon');
			copyElement.innerHTML = 'Copiado';
			setTimeout(function () {
				copyElement.classList.remove('copied-icon');
				copyElement.innerHTML = 'Copiar código do QR Code';
			}, 1000);
		});
	</script>
<?php endif;

