<?php /** @var $block \Magento\Checkout\Block\Onepage\Failure */ ?>

<div class="checkout-success ipag-checkout-failure">
    <?php if ($block->getRealOrderId()) : ?>
        <p><?= $block->escapeHtml(__('Seu pedido é o número %1.', $block->getRealOrderId())) ?></p>
    <?php endif; ?>

    <?php if ($error = $block->getErrorMessage()) : ?>
        <p><?= $block->escapeHtml($error) ?></p>
    <?php else : ?>
        <p><?= $block->escapeHtml(__('Não foi possível processar o seu pagamento.')) ?></p>
    <?php endif; ?>

    <?= $block->getChildHtml('ipag_order_failure') ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>">
                <span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        </div>
    </div>
</div>
