<?php

/**
 * Copyright © Ipag, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php /** @var $block \Ipag\Payment\Block\Success */ ?>

<div class="checkout-success">
	<?php if ($block->getOrderId()) : ?>
		<?php if ($block->getCanViewOrder()) : ?>
			<p><?= $block->escapeHtml(__('Your order number is: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeUrl($block->getViewOrderUrl()), $block->getOrderId())), ['a', 'strong']) ?></p>
		<?php else : ?>
			<p><?= $block->escapeHtml(__('Your order # is: <span>%1</span>.', $block->getOrderId()), ['span']) ?></p>
		<?php endif; ?>

		<?php $paymentStatus = $block->getInfo('payment.status'); ?>
		<?php $deniedStatuses = ['3', '7']; ?>
		<?php if (in_array($paymentStatus, $deniedStatuses) && $block->getMethodCode() == 'ipagcc') : ?>
			<p><?= $block->escapeHtml(__('Seu cartão não pode ser processado, entre em contato com sua operadora.'))
				?></p>
		<?php else : ?>
			<p><?= $block->escapeHtml(__('We\'ll email you an order confirmation with details and tracking info.')) ?></p>
		<?php endif; ?>
	<?php endif; ?>

	<?= $block->getAdditionalInfoHtml() ?>

	<div class="actions-toolbar">
		<div class="primary">
			<a class="action primary continue" href="<?= $block->escapeUrl($block->getContinueUrl()) ?>"><span><?= $block->escapeHtml(__('Continue Shopping')) ?></span></a>
		</div>
	</div>
</div>