<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$pixUrl = $block->getLinkPrintPay();
?>
<?=$block->escapeHtml($block->getMethod()->getTitle())?>

<table class="data-table admin__table-secondary">
<?php if ($specificInfo): ?>
    <?php foreach ($specificInfo as $label => $value): ?>
        <tr>
            <th><?=$block->escapeHtml($label)?>:</th>
            <td>
                <?=/* @noEscape */nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true))))?>
            </td>
        </tr>
    <?php endforeach;?>
<?php endif;?>
    <?php if ($pixUrl): ?>
        <tr>
            <th scope="row"><?=$block->escapeHtml('Link')?></th>
            <td>
                <a href="<?php echo $pixUrl; ?>" class="btn btn-link" target="_blank">
                    Visualizar QR Pix
                </a>
            </td>
        </tr>
    <?php endif;?>
</table>

<?=$block->getChildHtml()?>
